-- Create a table for posts
create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tags text[] default '{}'
);

-- Enable Row Level Security (RLS)
alter table posts enable row level security;

-- Create a policy that allows anyone to read posts
create policy "Public posts are viewable by everyone"
  on posts for select
  using ( true );

-- Create a policy that allows inserting posts (ideally restricted, but for this demo public or via anon key)
-- Note: In a real app, you'd restrict this to authenticated users or a service role.
-- Since the requirement is an open /api/new-post endpoint using the anon key (implied), we might need insert access for anon.
-- However, typically API routes use the SERVICE_ROLE_KEY to bypass RLS for administrative tasks.
-- But the prompt implies "external JSON data POST", which suggests the API handles the auth or is open.
-- If the API uses the `supabase` client initialized with anon key, RLS must allow insert.
-- Let's assume the API will handle validation and insertion.
-- If we want the API route to work without a service role key (using the client-side anon key is weird for a backend route, but common in simple setups), we need an insert policy.
-- BETTER APPROACH: The API route should ideally use a Service Role key if it's "admin" stuff, but standard Next.js API routes run on the server.
-- I'll add a policy for anon insert for simplicity of the "minimal blog" demo, but comment on security.

create policy "Enable insert for everyone (demo purpose)"
  on posts for insert
  with check ( true );
